#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jan 27 19:43:19 CET 2022
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto f1ecddbb7ecd4d1d8a563e8e64f75c5d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_uart_fir_filter_cascade_behav xil_defaultlib.tb_uart_fir_filter_cascade -log elaborate.log
